### ISSUE TITLE
Support custom users endpoint

### ISSUE THREAD

**Issue by shawnlauzon** [MichaelErmer/feathers-authentication-compatibility#1]
My Users service is not registered at `users`. Should allow the client to define a custom location, like the `auth.userEndpoint` option previously supported.

**Comment by MichaelErmer** [comment]
@shawnlauzon good point, I have very limited time the next days, but feel free to submit a PR.

**Comment by shawnlauzon** [comment]
@MichaelErmer Yep, will do!

**Comment by MichaelErmer** [comment]
Thanks for Contributing
